/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AirPodsPro2: typeof import('./src/components/airPodsPro2.vue')['default']
    AppleCard: typeof import('./src/components/appleCard.vue')['default']
    AppleIntelli: typeof import('./src/components/appleIntelli.vue')['default']
    AppleTradeIn: typeof import('./src/components/appleTradeIn.vue')['default']
    AppleWatch10: typeof import('./src/components/appleWatch10.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    IconsAppleIcon: typeof import('./src/components/icons/AppleIcon.vue')['default']
    IconsBreadIcon: typeof import('./src/components/icons/BreadIcon.vue')['default']
    IconsSearchIcon: typeof import('./src/components/icons/SearchIcon.vue')['default']
    IconsShoppingBagIcon: typeof import('./src/components/icons/ShoppingBagIcon.vue')['default']
    IPadMini: typeof import('./src/components/iPadMini.vue')['default']
    IPhone16: typeof import('./src/components/iPhone16.vue')['default']
    IPhone16Pro: typeof import('./src/components/iPhone16Pro.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
